learning rate:
  Fixed: 0.0001
  Cosine:
    initial_lr: 0.01
    final_lr: 0.0001
  Decay:
    initial_lr: 0.01
    final_lr: 0.0001
  Exponential:
    initial_lr: 0.01
    final_lr: 0.0001
momentum: 0.8
